name: app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  flutter_riverpod: ^3.1.0
  go_router: ^17.0.1
  logger: ^2.6.2
  json_annotation: ^4.9.0
  google_fonts: ^6.3.3
  font_awesome_flutter: ^10.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.11.2
  build_runner: ^2.10.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
